### PR TITLE
Feature/save as table operation lineage

### PR DESCRIPTION
**Pull request by ugoa**

### CODE REVIEW

**Comment by vackosar** [comment]
Would u use rebase feature to squash your commits into single one? Would you reference an issue id in the comment if there is any related issue?

**Comment by vackosar** [comment]
@ugoa perfect, I suggest to first respond to the rest of the comments and only at the end do the squashing as I am not sure how well github review will handle the squashing.

**Comment by ugoa** [comment]
@fmalpica-sbd Thanks for point out, I'd fixed on my local branch. Will update it when it's all together.

@vackosar I wonder if github could merge with `--no-ff` option?

**Comment by fmalpica-sbd** [comment]
@ugoa Anyway, I tried this code but there is some problem when it stores it on Mongodb because the web UI does not load it.

**Pull request closed without merging**
