### PR TITLE
#345: File separator issues prevent build on Windows

### PR DESCRIPTION
**Pull request by benedeki**
* Using ${file.separator} instead of / on the critical places

### CODE REVIEW

**Comment by leborgneromain** [comment]
LGTM

**Comment by wajda** [comment]
I might be wrong, but I thing using `${file.separator}` is an overkill. It makes plugin config harder to read, and is not equally necessary in different places.
For instance, in the Ant plugin commands are split by OS, so you can just use Windows backslash there:
```xml
<exec executable="cmd" osfamily="windows" failonerror="true">
    <arg line="/c node_modules\.bin\redoc-cli.cmd bundle -o ${swagger.output.path}\consumer.html ${swagger.output.path}\consumerSwagger.json"/>
    ...
</exec>
```  
In the other place - the Tomcat plugin - `<path>/</path>` elements denotes the Web-context name (root context n this case) - it;s a URI part, not a file system path. So, using backslash could event hurt here.

**Comment by benedeki** [comment]
>
>
> I think using `${file.separator}` is an overkill. It makes plugin config harder to read, and is not equally necessary in different places.
> For instance, in the Ant plugin commands are split by OS, so you can just use Windows backslash there:

I used it on the minimum required places needed. Sure the backslash can be used, but seems more brittle depending on the designation 
 
> In the other place - the Tomcat plugin - `<path>/</path>` elements denotes the Web-context name (root context n this case) - it;s a URI part, not a file system path. So, using backslash could event hurt here.

In this case the build actually eventually succeeds  But there's a big fat red ERROR in the build log. This removes it. Reportedly using `./` also works if you don't like `${file.separator}`.
Let's discuss Monday.

**Comment by benedeki** [comment]
The change is very different from the original PR. But it does address an error from the build log.
Second is a change in the `package-lock.json` in hope that after this commit it will remain stable.

**Pull request merged**
