### PR TITLE
Feature/540 forward lineage

### PR DESCRIPTION
**Pull request by dk1844**
Heavily inspired by (backward) Lineage. After the naive implementation, common parts of the foxx service have been moved to `commons.js` for reuse.

(Also, there is a similar PR #1092 - let's inspire each other, @vishalag001)

### Spline service level API
`GET /spline/events/$eventId/lineage-overview/$maxDepth`
 - yields the impact (forward lineage) graph object
 
### ArangoDB foxx-service level API
`GET /events/:eventKey/impact-overview/:maxDepth`
 - yields the impact (forward lineage) graph object (from `persistence`)

## Test-run
I have hacked the spline-ui to load `.../impact-overview` url instead of `.../lineage-overview` to test the graph data in UI to be shown:

hacked-ui-to-show-impact-overview

Implements backed of #540.

### CODE REVIEW

**Comment by dk1844** [comment]
@wajda @cerveada At this point, the solution seems to work. Is it worth, or rather, to what degree should I try to deduplicate with the original code - there are quite obviously some similar parts...?

**Comment by wajda** [comment]
> @wajda @cerveada At this point, the solution seems to work. Is it worth, or rather, to what degree should I try to deduplicate with the original code - there are quite obviously some similar parts...?

It's up to you. Of course the code quality is important, and I don't think any AQL or FOXX code has any special additions or exceptions related to the common code quality standards. Just use a usual common sense. When you're done mark it as "ready for review" and we'll take a look.

**Comment by cerveada** [comment]
What is a purpose of the two empty files?

**Comment by dk1844** [comment]
> What is a purpose of the two empty files?

After some digging, I have discovered that it was due to file mode being inadvertently changed - probably when sharing between Win-Linux/etc while having git's `core.filemode` enabled. Some details [here](https://stackoverflow.com/a/56388238). The default settings always changed my file mode even if I reverted any changes.

So I have set `git config core.filemode false` on my cloned repo on Windows and I have reverted the files to the original state 👍 . Thanks for noticing

**Review by cerveada — APPROVED** [review]

**Comment by dk1844** [comment]
Closed in favor of https://github.com/AbsaOSS/spline/pull/1100

**Pull request closed without merging**
